services:
  app:
    build:
      context: ./deploy/php/
      dockerfile: local.Dockerfile
    volumes:
      - .:/var/www
      - ./deploy/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - airport-search
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - .:/var/www:rw
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - redis
    networks:
      - airport-search
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/pgdata:/var/lib/postgresql/data
    networks:
      - airport-search
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./deploy/redisdata:/data
    restart: unless-stopped
    networks:
      - airport-search
networks:
  airport-search:
